// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqgktgrtovuejtvshmue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZ2t0Z3J0b3Z1ZWp0dnNobXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjY4MzIsImV4cCI6MjA2MzM0MjgzMn0.5zk72UdKgH3XxJgVCHEqxgbi7mjjPLFLRlaXo4ZKf9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);